## This configuration was generated by terraform-provider-oci

# Data source to get all OCI services (region-agnostic)
data "oci_core_services" "all_services" {
  filter {
    name   = "name"
    values = ["All .* Services In Oracle Services Network"]
    regex  = true
  }
}

resource "oci_core_nat_gateway" "export_NAT--vcn01" {
  block_traffic  = "false"
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  display_name = "NATゲートウェイ-vcn01"
  freeform_tags = {
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_vcn01.id
}

resource "oci_core_default_dhcp_options" "export_Default-DHCP-Options-for-vcn01" {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  display_name     = "Default DHCP Options for vcn01"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_vcn01.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "vcn01.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource "oci_core_internet_gateway" "export_--vcn01" {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  display_name = "インターネット・ゲートウェイ-vcn01"
  enabled      = "true"
  freeform_tags = {
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_vcn01.id
}

resource "oci_core_subnet" "export_--vcn01_1" {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.1.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-vcn01.id
  display_name    = "プライベート・サブネット-vcn01"
  freeform_tags = {
  }
  ipv4cidr_blocks = [
    "10.0.1.0/24",
  ]
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_route-table-for-private--vcn01.id
  security_list_ids = [
    oci_core_security_list.export_--vcn01-.id,
  ]
  vcn_id = oci_core_vcn.export_vcn01.id
}

resource "oci_core_subnet" "export_--vcn01_2" {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.0.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-vcn01.id
  display_name    = "パブリック・サブネット-vcn01"
  freeform_tags = {
  }
  ipv4cidr_blocks = [
    "10.0.0.0/24",
  ]
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_vcn01.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_vcn01.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_vcn01.id
}

resource "oci_core_vcn" "export_vcn01" {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  display_name = "vcn01"
  dns_label    = "vcn01"
  freeform_tags = {
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
  security_attributes = {
  }
}

resource "oci_core_security_list" "export_--vcn01-" {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  display_name = "プライベート・サブネット-vcn01のセキュリティ・リスト"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_vcn01.id
}

resource "oci_core_default_security_list" "export_Default-Security-List-for-vcn01" {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  display_name = "Default Security List for vcn01"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_vcn01.default_security_list_id
}

resource "oci_core_route_table" "export_route-table-for-private--vcn01" {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  display_name = "route table for private プライベート・サブネット-vcn01"
  freeform_tags = {
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_NAT--vcn01.id
    route_type        = "STATIC"
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "all-ord-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.export_--vcn01_3.id
    route_type        = "STATIC"
  }
  vcn_id = oci_core_vcn.export_vcn01.id
}

resource "oci_core_default_route_table" "export_default-route-table-for-vcn01" {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  display_name = "default route table for vcn01"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_vcn01.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_--vcn01.id
    route_type        = "STATIC"
  }
}

resource "oci_core_service_gateway" "export_--vcn01_3" {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  display_name = "サービス・ゲートウェイ-vcn01"
  freeform_tags = {
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = data.oci_core_services.all_services.services[0].id
  }
  vcn_id = oci_core_vcn.export_vcn01.id
}

