## This configuration was generated by terraform-provider-oci

resource "oci_datascience_project" "export_rag_project" {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  description  = "Data Science用のプロジェクト"
  display_name = "rag_project"
  freeform_tags = {
  }
}

resource "oci_datascience_notebook_session" "export_rag_notebook" {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  display_name = "rag_notebook"
  freeform_tags = {
  }
  notebook_session_config_details {
    block_storage_size_in_gbs = "50"
    notebook_session_shape_config_details {
      cpu_baseline  = ""
      memory_in_gbs = "24"
      ocpus         = "4"
    }
    #private_endpoint_id = <<Optional value not found in discovery>>
    shape     = "VM.Standard.A1.Flex"
    subnet_id = oci_core_subnet.export_--vcn01_1.id
  }
  notebook_session_configuration_details {
    block_storage_size_in_gbs = "50"
    notebook_session_shape_config_details {
      cpu_baseline  = ""
      memory_in_gbs = "24"
      ocpus         = "4"
    }
    #private_endpoint_id = <<Optional value not found in discovery>>
    shape     = "VM.Standard.A1.Flex"
    subnet_id = oci_core_subnet.export_--vcn01_1.id
  }
  notebook_session_runtime_config_details {
    custom_environment_variables = {
    }
    notebook_session_git_config_details {
    }
  }
  project_id = oci_datascience_project.export_rag_project.id
  state      = "ACTIVE"
}

