## This configuration was generated by terraform-provider-oci

resource "oci_database_autonomous_database" "export_ragdb" {
  admin_password = var.db_admin_password
  #are_primary_whitelisted_ips_used = <<Optional value not found in discovery>>
  #auto_refresh_frequency_in_seconds = <<Optional value not found in discovery>>
  #auto_refresh_point_lag_in_seconds = <<Optional value not found in discovery>>
  #autonomous_container_database_id = <<Optional value not found in discovery>>
  #autonomous_database_backup_id = <<Optional value not found in discovery>>
  #autonomous_database_id = <<Optional value not found in discovery>>
  autonomous_maintenance_schedule_type = "REGULAR"
  backup_retention_period_in_days      = "7"
  #byol_compute_count_limit = <<Optional value not found in discovery>>
  character_set = "AL32UTF8"
  compartment_id = var.compartment_ocid
  compute_count           = "2"
  compute_model           = "ECPU"
  cpu_core_count          = "0"
  data_safe_status        = "NOT_REGISTERED"
  data_storage_size_in_gb = "50"
  #data_storage_size_in_tbs = <<Optional value not found in discovery>>
  db_name = "ragdb"
  db_tools_details {
    compute_count            = "32"
    is_enabled               = "true"
    max_idle_time_in_minutes = "10"
    name                     = "DLA"
  }
  db_tools_details {
    compute_count            = "8"
    is_enabled               = "true"
    max_idle_time_in_minutes = "60"
    name                     = "GRAPH_STUDIO"
  }
  db_tools_details {
    compute_count            = "8"
    is_enabled               = "true"
    max_idle_time_in_minutes = "30"
    name                     = "DATA_TRANSFORMS"
  }
  db_tools_details {
    compute_count            = "8"
    is_enabled               = "true"
    max_idle_time_in_minutes = "60"
    name                     = "OML"
  }
  db_version  = "26ai"
  db_workload = "OLTP"
  defined_tags = {
  }
  #disaster_recovery_type = <<Optional value not found in discovery>>
  display_name = "ragdb"
  #enable_delete_scheduled_operations = <<Optional value not found in discovery>>
  encryption_key {
    #arn_role = <<Optional value not found in discovery>>
    autonomous_database_provider = "ORACLE_MANAGED"
    #certificate_directory_name = <<Optional value not found in discovery>>
    #certificate_id = <<Optional value not found in discovery>>
    #directory_name = <<Optional value not found in discovery>>
    #external_id = <<Optional value not found in discovery>>
    #key_arn = <<Optional value not found in discovery>>
    #key_name = <<Optional value not found in discovery>>
    #key_ring = <<Optional value not found in discovery>>
    #kms_key_id = <<Optional value not found in discovery>>
    #kms_rest_endpoint = <<Optional value not found in discovery>>
    #location = <<Optional value not found in discovery>>
    #okv_kms_key = <<Optional value not found in discovery>>
    #okv_uri = <<Optional value not found in discovery>>
    #project = <<Optional value not found in discovery>>
    #service_endpoint_uri = <<Optional value not found in discovery>>
    #vault_id = <<Optional value not found in discovery>>
    #vault_uri = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  #in_memory_percentage = <<Optional value not found in discovery>>
  #is_access_control_enabled = <<Optional value not found in discovery>>
  is_auto_scaling_enabled             = "true"
  is_auto_scaling_for_storage_enabled = "false"
  is_backup_retention_locked          = "false"
  is_data_guard_enabled               = "false"
  is_dedicated                        = "false"
  #is_dev_tier = <<Optional value not found in discovery>>
  #is_disable_db_version_upgrade_schedule = <<Optional value not found in discovery>>
  #is_disconnect_peer = <<Optional value not found in discovery>>
  is_free_tier                = "false"
  is_local_data_guard_enabled = "false"
  is_mtls_connection_required = "false"
  #is_preview_version_with_service_terms_accepted = <<Optional value not found in discovery>>
  #is_refreshable_clone = <<Optional value not found in discovery>>
  #is_replicate_automatic_backups = <<Optional value not found in discovery>>
  #is_schedule_db_version_upgrade_to_earliest = <<Optional value not found in discovery>>
  #key_version_id = <<Optional value not found in discovery>>
  kms_key_id    = "ORACLE_MANAGED_KEY"
  license_model = "LICENSE_INCLUDED"
  #local_adg_auto_failover_max_data_loss_limit = <<Optional value not found in discovery>>
  #max_cpu_core_count = <<Optional value not found in discovery>>
  ncharacter_set = "AL16UTF16"
  nsg_ids = [
  ]
  #ocpu_count = <<Optional value not found in discovery>>
  open_mode                  = "READ_WRITE"
  operations_insights_status = "NOT_ENABLED"
  #peer_db_id = <<Optional value not found in discovery>>
  permission_level = "UNRESTRICTED"
  #private_endpoint_ip = <<Optional value not found in discovery>>
  #private_endpoint_label = <<Optional value not found in discovery>>
  #refreshable_mode = <<Optional value not found in discovery>>
  #remote_disaster_recovery_type = <<Optional value not found in discovery>>
  #resource_pool_leader_id = <<Optional value not found in discovery>>
  resource_pool_summary {
    is_disabled = "true"
    #pool_size = <<Optional value not found in discovery>>
  }
  #rotate_key_trigger = <<Optional value not found in discovery>>
  #secret_id = <<Optional value not found in discovery>>
  #secret_version_number = <<Optional value not found in discovery>>
  security_attributes = {
  }
  #shrink_adb_trigger = <<Optional value not found in discovery>>
  #source = <<Optional value not found in discovery>>
  #source_id = <<Optional value not found in discovery>>
  standby_whitelisted_ips = [
  ]
  state = "AVAILABLE"
  #subnet_id = <<Optional value not found in discovery>>
  #subscription_id = <<Optional value not found in discovery>>
  #switchover_to = <<Optional value not found in discovery>>
  #switchover_to_remote_peer_id = <<Optional value not found in discovery>>
  #time_of_auto_refresh_start = <<Optional value not found in discovery>>
  #time_scheduled_db_version_upgrade = <<Optional value not found in discovery>>
  #timestamp = <<Optional value not found in discovery>>
  #use_latest_available_backup_time_stamp = <<Optional value not found in discovery>>
  vanity_url_details {
    #api_gateway_id = <<Optional value not found in discovery>>
    is_disabled = "true"
    #vanity_url_host_name = <<Optional value not found in discovery>>
  }
  #vault_id = <<Optional value not found in discovery>>
  whitelisted_ips = [
    "${oci_core_vcn.export_vcn01.id};10.0.1.0/24",
  ]
}

